# Generated by Django 4.2.7 on 2024-01-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='core/images'),
        ),
    ]
